trava: add encoding declaration.
This makes the error message more helpful when accidentally using Python
2.X.

Before:

    $ python trava
      File "trava", line 3
    SyntaxError: Non-ASCII character '\xc2' in file trava on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

After:

    $ python trava
    Traceback (most recent call last):
      File "trava", line 24, in <module>
        from lib import cli
      File ".../lib/__init__.py", line 1
        lambda: (yield from 0)  # Python >= 3.3 is required
                          ^
    SyntaxError: invalid syntax