lib.colors: add missing colors for (un)reverse.
Fixes:

    Traceback (most recent call last):
      ...
      File ".../trava/lib/colors.py", line 46, in format
        for key, value in kwargs.items()
      File ".../trava/lib/colors.py", line 46, in <dictcomp>
        for key, value in kwargs.items()
      File ".../trava/lib/colors.py", line 40, in _quote
        return ''.join(esc())
      File ".../trava/lib/colors.py", line 37, in esc
        yield _quote_unsafe(s)
      File ".../trava/lib/colors.py", line 28, in _quote_unsafe
        return ''.join(map(_quote_unsafe_char, s))
      File ".../trava/lib/colors.py", line 23, in _quote_unsafe_char
        return '{t.reverse}^{c}{t.unreverse}'.format(t=_seq, c=chr(ord('@') ^ ord(ch)))
    AttributeError: type object '_seq' has no attribute 'reverse'